# Makefile for compilation with gcc

# Include directory for Nabbit.
NABBIT_INCLUDES = -I $(UTIL_DIR) -I $(NABBIT_DIR) -I $(ARRAYS_DIR)

CC=gcc
CXX=g++
CILKVIEW_FLAGS=
LIBARG= -lpthread

CFLAGS = -Wall -O3 -fcilkplus
CXXFLAGS = $(CFLAGS) -std=c++0x
CILK_SERIALIZE_FLAG = -cilk-serialize
